### ISSUE TITLE
Possible to reply to posts? 

### ISSUE THREAD

**Issue by DickinsonSa** [nick-delirium/lemmy-fennec#12]
Not sure where I would do this, but so far I haven't been able to effect a reply to any posts.

Is this a missing feature?

Fantastic looking app btw - can't wait for it to develop.

**Comment by nick-delirium** [comment]
Yeah, replying, as well as other important features, are still [in the roadmap](https://github.com/users/nick-delirium/projects/2). I'll start working on it as soon as I will finish more or less working profile view + saved posts view, which will take a couple of days.

**Comment by DickinsonSa** [comment]
Thanks for clearing that up. I look forward to giving it a spin when you're into your roadmap. Looking pretty good so far though - nice job.

**Comment by nick-delirium** [comment]
Now you can create and comment on posts, with fairly basic functionality, but it works and covers most needs. I will, of course, improve this functionality in the next versions.
