### ISSUE TITLE
clicking next page on an empty search crashes the app

### ISSUE THREAD

**Issue by ContentSpy** [nick-delirium/lemmy-fennec#13]
When you search for something that doesn't exist a next page button is on screen when clicked it crashes the app

**Comment by ContentSpy** [comment]
Here is a video:


https://github.com/nick-delirium/lemmy-fennec/assets/91404729/ec5173ae-63c5-4ff4-9b7d-d0aa01742cf7

**Comment by nick-delirium** [comment]
Awesome find, thanks. Will be fixed in today's build.

**Comment by nick-delirium** [comment]
[Fixed with new pagination component](https://github.com/nick-delirium/lemmy-fennec/releases/tag/0.0.1-alpha.2)
