### ISSUE TITLE
upvotes don't seem to register until refresh

### ISSUE THREAD

**Issue by ContentSpy** [nick-delirium/lemmy-fennec#14]
Upvoting a post doesn't seem to register in the upvote counter until refreshed

**Comment by ContentSpy** [comment]
It only registers when your in the post but doesn't when your in your feed (it seems to register but the visual just isn't there)

Here is a video of it:


https://github.com/nick-delirium/lemmy-fennec/assets/91404729/f4ca90c0-0b3c-4179-a0b3-89af01132352

**Comment by nick-delirium** [comment]
I think the problem is largely fixed everywhere for now. Please open new issue if you'll face any problems with voting
