### ISSUE TITLE
Header above the feed doesn't update when changing feed type

### ISSUE THREAD

**Issue by theboomr** [nick-delirium/lemmy-fennec#2]
If I change the feed type to Subscribed or All, the header still persistently says Local no matter what. The sorting type updates as expected, but not the feed type.

**Comment by nick-delirium** [comment]
Should be fixed in [this commit](https://github.com/nick-delirium/lemmy-fennec/commit/cd61aead9a2e5eb8ced4b0d5705184f60964fe23)

**Comment by nick-delirium** [comment]
Should be fixed with [0.0.3-rc release](https://github.com/nick-delirium/lemmy-fennec/releases/tag/0.0.3-rc), don't hesitate to reopen if this will still happen.
