### ISSUE TITLE
Feature Request: Add ability to open images directly from feed

### ISSUE THREAD

**Issue by theboomr** [nick-delirium/lemmy-fennec#20]
Personally I would find it nice if tapping on an image/media from the feed just directly opens it in fullscreen, as opposed to opening the post view first, where I then have to tap a second time to open the media fullscreen.

**Comment by nick-delirium** [comment]
thats a good point, I was thinking about it as well

**Comment by theboomr** [comment]
The new functionality does not work if viewing the feed in compact mode
