### ISSUE TITLE
Feature Request: Add the collapse button on single/isolated comments too

### ISSUE THREAD

**Issue by theboomr** [nick-delirium/lemmy-fennec#21]
Currently, the collapse button only shows up if a comment has replies. But sometimes I still want to collapse a single large comment that doesn't have a chain/thread beneath it, just to get it out of the way visually.

**Comment by nick-delirium** [comment]
fixed with https://github.com/nick-delirium/lemmy-fennec/commit/91cb2c368651b12457d1e63decc9cf8aba65a1e7

**Comment by theboomr** [comment]
It seems like in the latest release this doesn't work still, if I tap on a comment that has no children it does not collapse. It also doesn't work if it does have children but they are collapsed by default and haven't yet been expanded.
