### ISSUE TITLE
Feature Request: Add a way to share media/image files directly, rather than just the link to the post

### ISSUE THREAD

**Issue by theboomr** [nick-delirium/lemmy-fennec#22]
Maybe implement this so that tapping the share button from fullscreen will share the media file? And keep the behavior of the share button the same from the regular post screen or feed. Alternately, there could be some sort of pop-up dialog asking which thing you want to share, post link, or media file, from any of the 3 locations with the share button present.

**Comment by nick-delirium** [comment]
Weird, this is what I see when I tap share inside image viewer:
<img width="240" src="https://github.com/nick-delirium/lemmy-fennec/assets/23126999/ddd42ec6-fc8f-466f-a23d-6274e9019fc6">

> Alternately, there could be some sort of pop-up dialog asking which thing you want to share, post link, or media file, from any of the 3 locations with the share button present.

Adding it to my todos since its not a few line change

**Comment by theboomr** [comment]
So, yes when you share from the full screen view, it does link to the image directly, but I was talking more like downloading the media and sharing the downloaded file, not just sharing a link

**Comment by theboomr** [comment]
Speaking of which, just a way to download media would also separately be a nice thing too
