### ISSUE TITLE
Feature Request: Make comment text selectable/copyable somehow

### ISSUE THREAD

**Issue by theboomr** [nick-delirium/lemmy-fennec#24]
Currently, there is no action for tapping or long-pressing on the body of a comment. With this in mind, you could make text just directly selectable by long-pressing on the text. Alternately, if you had some other functionality/feature in mind to implement later by long-pressing on a comment, you could add a 3-dot/overflow menu to comments that has an option to separately bring up the comment text in a popup that lets you select and copy as you wish.

**Comment by nick-delirium** [comment]
second option (with dot menu) looks easier since it will require less work, but I will raise an issue on md renderer library I use, should be easy to add selectable prop to their text fields from their side

**Comment by theboomr** [comment]
Sounds good. Have to say I really love seeing how quickly and simply you're able to implement a lot of these feature requests! If I had more actual spare time I would probably try to actually look at the code and learn how to do React so I could contribute, but unfortunately I very much do not have the extra time currently lol

**Comment by nick-delirium** [comment]
Thats okay, you're already helping with testing and ideas :)

**Comment by nick-delirium** [comment]
Added a way to copy entire comment, still working out the solution to select text ^

**Comment by nick-delirium** [comment]
After few tries, it will be a disaster in terms of mixing collapse action and select, so lets keep this way of copying while I'm thinking about new one for the future.
