### ISSUE TITLE
Feature Request: Make comments collapse by tapping on the comment, rather than using a whole separate button underneath the comment

### ISSUE THREAD

**Issue by theboomr** [nick-delirium/lemmy-fennec#25]
This is definitely a personal preference thing, so if you don't want to implement this you can feel free to close this issue, but I like being able to collapse comments just by tapping on the comment, cause it's slightly easier and quicker than aiming for the specific collapse button under the comment.

**Comment by nick-delirium** [comment]
Agree, current implementation was made like a work around at that moment. Right now is the good time to add proper thingie

**Comment by nick-delirium** [comment]
fixed with https://github.com/nick-delirium/lemmy-fennec/commit/91cb2c368651b12457d1e63decc9cf8aba65a1e7
