### ISSUE TITLE
Hide read posts doesn't seem to work

### ISSUE THREAD

**Issue by theboomr** [nick-delirium/lemmy-fennec#3]
I see the option in settings for hiding read posts, but if I toggle it on, read posts still show in my feed anyway.

(Also, would love to see a feature where you can just hide posts you've voted on)

**Comment by nick-delirium** [comment]
This is probably tied to lemmy instance you're using since apps can just change this setting in your profile settings (same as on web) and then during fetch DB/API decides what posts to return based on this setting. Maybe its not working (in general) or being overwritten by sticky posts?

> (Also, would love to see a feature where you can just hide posts you've voted on)

Turned it on by default in [this commit](https://github.com/nick-delirium/lemmy-fennec/commit/cd61aead9a2e5eb8ced4b0d5705184f60964fe23), will build it in a few days when I'll have more things ready.

**Comment by theboomr** [comment]
Will try to investigate more once you post the next release, thanks! Btw I'm really liking the foundation you're building in this app, feels like it could end up being my main app for lemmy. The UI feels more bottom-focused (which I love), though I don't know if that is a primary intention of yours or not

**Comment by nick-delirium** [comment]
> The UI feels more bottom-focused (which I love), though I don't know if that is a primary intention of yours or not

Yeah, as someone with big phone (pixel 7p) I hate when I have to reach to the top for basic functinality so I'm intentionally trying to concentrate as much buttons/toggles on the bottom as possible, I'm also thinking about making left/right handed toggle as well 👀

**Comment by theboomr** [comment]
That is awesome to hear! I feel the same way, even using a smaller phone (S23), so knowing there's at least one lemmy app that is specifically focused on one hand usability is very exciting 🙂

Also I am left handed so a toggle to focus everything to the left side would be really excellent for me!!

**Comment by theboomr** [comment]
So the new `Hide read posts` option in the hamburger menu is definitely useful in this release, if I tap that, all the read posts do in fact get hidden! I'm noticing now, regarding the option to hide read posts in my profile in the app, that setting seems to just not be syncing to my lemmy.world profile correctly. I just changed that option on my profile on the actual website, saved it, restarted Fennec, and then it was staying turned on in the app's profile page, and working correctly on feed refresh without having to use the option in the hamburger menu.

**Comment by nick-delirium** [comment]
I think lemmy.world is having a bad time right now tbh, I'm using it as well and they're having outages and problems with api versions (for example their login request leads to 404), I'll see if I can actually login there and reproduce it, but things seems to be working on lemmy.ml

**Comment by nick-delirium** [comment]
Ok, added a loader in new release so it should be less confusing. Instances seems to be more stable now than few days before. 

Btw, @theboomr I created a community for this app, so you can chat with me there if you want to.
