### ISSUE TITLE
Bug: comment action buttons overlap with vertical nested line indicators

### ISSUE THREAD

**Issue by theboomr** [nick-delirium/lemmy-fennec#31]
At least on my phone, this starts happening when a comment is 6 replies deep. Best solution is probably to limit the number of indents that can be displayed and show a button that opens a secondary screen with the further replies re-aligned to the left.

**Comment by nick-delirium** [comment]
please add screenshots or link to problematic post next time if possible :)

**Comment by theboomr** [comment]
> please add screenshots or link to problematic post next time if possible :)

Yes, sorry about that! I try to do that usually but when I submitted this one I was in a bit of a rush and just wanted to submit the bug report while I was thinking about it so I neglected to realize that a link to a thread exhibiting the issue would've been very useful.
