### ISSUE TITLE
Improvement: show "Media saved" when downloaded media

### ISSUE THREAD

**Issue by Morethanevil** [nick-delirium/lemmy-fennec#33]
Hi morethanevil here, who commented to your survey 😁

I have one more idea. It is easy possible to save videos and pictures, but I don't get a notification if it was successful. I need to look by myself in the DCIM folder. 

It would be cool if the app shows an inapp status if media was downloaded properly. 

Bonuspoints for saving media in a separate folder "articus" and not between camera pictures 🐱

Thank you for the app and your effort

**Comment by nick-delirium** [comment]
Added in 403ec94
