### ISSUE TITLE
Bug: opening a link from comments shows instantly "netwoek error"

### ISSUE THREAD

**Issue by Morethanevil** [nick-delirium/lemmy-fennec#34]
I tried to follow a link for Quillpad from this post https://feddit.uk/comment/1577083

I got network error, on the my mobil instance page it works. When I press the back button it goes straight to.the time instead of previous post.

Android 13, latest Arctius release from playstore.

**Comment by nick-delirium** [comment]
Couldn't reproduce it properly, can you please post a comment with that link in our community so I can test it?

**Comment by Morethanevil** [comment]
It was in[ this post](https://feddit.uk/post/1001064), the user with the comment about Quillpad. I made a video and posted it as you wished

https://github.com/nick-delirium/lemmy-fennec/assets/110860055/2540973b-5e2e-4e51-95d4-fcbe9678b776

**Comment by nick-delirium** [comment]
fixed [here](https://github.com/nick-delirium/lemmy-fennec/releases/tag/0.1.6)

**Comment by nick-delirium** [comment]
btw "netwoek" comes from lemmy api lmao
