### ISSUE TITLE
External links don't show up in posts

### ISSUE THREAD

**Issue by theboomr** [nick-delirium/lemmy-fennec#4]
Both in the feed and after tapping on a post, if the post has a link, it does not show up anywhere that I can see. I attached a comparison pic between the Liftoff app and Fennec to show what I mean about a missing link, and [here's a link to that post](https://lemmy.world/post/774339)

![Screenshot_20230629_165958](https://github.com/nick-delirium/lemmy-fennec/assets/12604903/03f5f812-4fb1-46a8-85bf-ef7539ce3986)
![Screenshot_20230629_170033_fennec](https://github.com/nick-delirium/lemmy-fennec/assets/12604903/d569fb2c-5a06-41ca-bbb9-5c899dc695a6)
![Screenshot_20230629_170059_fennec](https://github.com/nick-delirium/lemmy-fennec/assets/12604903/69d0d011-f767-419a-b43a-10df88ecaa92)

**Comment by nick-delirium** [comment]
good catch, I totally forgot about links. Checking it off the list now, still have gifs, videos and full screen images to handle 🥲

**Comment by nick-delirium** [comment]
Fixed in new build in releases.
