### ISSUE TITLE
Reverse upvote/downvote arrow colors

### ISSUE THREAD

**Issue by theboomr** [nick-delirium/lemmy-fennec#5]
This isn't a critical one at all, but maybe consider reversing the colors to match what the lemmy website shows, so blue for upvote and orange for downvote

**Comment by nick-delirium** [comment]
My plan was to use red for up and blue for down because that's what I usually see in other apps to be honest, lets see if I'll get more users to give feedback on this one.

**Comment by theboomr** [comment]
Yeah this one is very minor to me, I ultimately don't care that much, but it does just seem like a "lemmy thing" that the colors are reversed, so 🤷‍♂️

**Comment by nazaradeh** [comment]
This could easily be a setting we could change if there are enough people with different opinions on this.

**Comment by nick-delirium** [comment]
will be in settings -> looks -> "swap vote button colors"
