### ISSUE TITLE
In lefty mode, the hamburger button shifts to the right after tapping

### ISSUE THREAD

**Issue by theboomr** [nick-delirium/lemmy-fennec#6]
First of all, thank you for implementing the lefty mode so quickly, love it!! I don't think I've ever seen the actual popup button moved to the left side in any other app even in ones with lefty modes, so this is really nice.

This issue is definitely just a small nit, but right now, when you tap the hamburger button in lefty mode, it shifts a bit to the right to be right-aligned under the menu items that popup above it. Still well within reach, but ideally it would match the regular/righty behavior where it stays aligned with the edge of the screen instead of shifting.

**Comment by nick-delirium** [comment]
should be fixed in next build

**Comment by nick-delirium** [comment]
Fixed in new build in releases.
