### ISSUE TITLE
Collapse parent comment along with child comments

### ISSUE THREAD

**Issue by theboomr** [nick-delirium/lemmy-fennec#7]
This is a personal preference thing, so ideally it would be user-configurable, but I personally really prefer having the top parent comment collapse all the way down as well, not just the child comments, that way longer comments don't keep taking up so much space while I scroll through.

**Comment by nick-delirium** [comment]
will be addressed in next build, great suggestion.

**Comment by nick-delirium** [comment]
Included as a new option in new build in releases.
