### ISSUE TITLE
Tap comments number/button from feed to jump straight to comments under post

### ISSUE THREAD

**Issue by theboomr** [nick-delirium/lemmy-fennec#8]
This is nice to have for posts where I know I want to skip past the OP and jump straight to all the comments

**Comment by nick-delirium** [comment]
I'm planning to add this, but as of right now its not quite simple (virtualized lists require to provide defined item height to be able to scroll by index) and will require some rewriting to do, I'll leave it for later (after I'll finish more important things like commenting)

**Comment by nick-delirium** [comment]
Should work now, plus you can click same icon to comment on the post itself once its open.
